name: 'gpt translator'
description: 'action to help translate changed file, it uses the open powershell module to do this, it can use openai service or azure openai service.'
inputs:
  openai_api_key:
    description: 'openai api key'
    required: true
  files:
    description: 'files to translate'
    required: true
  systemPrompt:
    description: 'system prompt'
    required: true
    default: You have me to translate the content to English, in professional style.You mustn't change the content structure and anything else, you just translate the content based on your language skill.
  from_language:
    description: 'from language'
    required: true
    default: zh
  to_language:
    description: 'to language'
    required: true
    default: en
runs:
  using: composite
  steps:
    - name: translate
      shell: pwsh
      env:
        files: ${{inputs.files}}
        system: ${{inputs.systemPrompt}}
        openai_api_key: ${{inputs.openai_api_key}}
      run: |
        Set-PSRepository -InstallationPolicy Trusted -Name PSGallery
        Install-Module -Name code365scripts.openai
        Import-Module code365scripts.openai
        $env:files | ConvertFrom-Json | ForEach-Object { 
          $file = $_ -replace "zh", "en";
          New-Item -Path $file -ItemType File -Force;
          chat -system $env:system -prompt $_ -api_key $env:openai_api_key | Out-File $file;
        }        